# this is written by the kcm-o, but we initialize here to cleanly handle the adoption case
apiVersion: v1
kind: ConfigMap
metadata:
  name: csr-controller-ca
  namespace: openshift-config-managed
  annotations:
    "openshift.io/owning-component": "kube-controller-manager"
data:
  ca-bundle.crt: |
    {{ .Assets | load "kubelet-client-ca-bundle.crt" | indent 4 }}

